project:
  type: website

website:
  title: "Dr. Stanciu"
  favicon: img/favicon.png
  cookie-consent:
    type: express
    style: headline
  google-analytics: 
    tracking-id: G-VLRYTQT397
    anonymize-ip: true
  navbar:
    tools: 
      - icon: github
        href: https://github.com/adrianvstanciu
      - icon: google
        href: https://scholar.google.com/citations?user=vy80cu8AAAAJ&hl=en
    left:
      - href: index.qmd
        text: News
      - text: Research
        menu: 
          - res.qmd
          - phd.qmd
          - gold.qmd
      - href: outreach.qmd
        text: Outreach
      - href: pub.qmd
        text: Publications
      - href: ppt.qmd
        text: Presentations
      - text: Teaching
        menu: 
          - teach.qmd
          - workshp.qmd
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



