---
title: "Publications"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VLRYTQT397"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VLRYTQT397');
</script>


:::{.panel-tabset}
### Peer-reviewed

## 2025

1. Buenconsejo, J. U., Ferrer-Wreder, L., Dimitrova, R., Pavlova, I., Bosnar, K., Bartoluci, S.,...**Stanciu, A.,**... Altansukh, S. (2025). Global profiles of positive youth development: A person-oriented analysis among emerging adults living in 21 countries. Journal of Youth and Adolescence, (online first). <https://doi.org/10.1007/s10964-025-02174-z>

## 2024

1. Stanciu, A. (2024). Values in psychological network systems compared across groups. _under review at PLoS One_ (read [preprint here](https://osf.io/vewf9))

2. Smallenbroek, O. & Stanciu, A. (2024). Age and gender differences in the value development of Dutch adults in 11 years of longitudinal data. Journal of Research in Personality, 113: 104540. <https://doi.org/10.1016/j.jrp.2024.104540>

3. Stanciu, A., Partsch, M. V., & Lechner, C. (2024). Basic human values and the adoption of cryptocurrency. Frontiers in Psychology, 15: 1395674. <https://doi.org/10.3389/fpsyg.2024.1395674> [open access]

## 2023 
1. Smallenbroek, O., **Stanciu, A.**, Arant, R., & Boehnke, K. (2023). Are values stable throughout adulthood? Evidence from two German long-term panel studies. PloS One, 18(11), e0289487. [open access](https://doi.org/10.1371/journal.pone.0289487)

2. Jovanovic, V., Rudnev, M., Abdelrahman, M., Kadir, N.B.A., Adebayo, D.F., Akaliyski, P....**Stanciu, A.,**...Yu, Y.Y. (2023). The coronavirus anxiety scale: Cross-national measurement invariance and convergent validity evidence. Psychological Assessment, Advance online publication. [open access](https://doi.org/10.1037/pas0001270)

3. Karakulak, A., Tepe, B. Dimitrova, R., Abdelrahman, M., Akaliyski, P., Alaseel, R.R...**Stanciu, A.,**...Zanoni da Silva, M. (2023). Empathy, fear of disease and support for COVID-19 containment behaviors: Evidence from 34 counties on the moderating role of governmental trust. Communications Psychology, 1, 43. [open access](https://doi.org/10.1038/s44271-023-00046-5)

4. Zhang, X., English, A.S., Li, X., Yang, Y., **Stanciu, A.,** & Shuang, W. (2023). International students' collective resilience in crisis: Sense of community predicts less anxiety via social contact and social support during lockdown. Heliyon, 9(4), 1-10. [open access](https://doi.org/10.1016/j.heliyon.2023.e15298).

## 2022
1. Witte, E.H., **Stanciu, A.**, & Zenker, F. (2022). Predicted as observed? How to identify empirically adequate theoretical constructs? Frontiers in Psychology: Theoretical and Philosophical Psychology, 13:980261. [open access](https://doi.org/10.3389/fpsyg.2022.980261)

2. Friehs, M.-T., Kotzur, P.F., Kraus, C., Schemmerling, M., Herzig, J., **Stanciu, A**...Yzerbyt, V. (2022). Evidence from 35 countries that social perception of key protagonists was associated with people’s acceptance of containment measures during COVID-19 pandemic. Scientific Reports, 12, 21277. [open access](https://doi.org/10.1038/s41598-022-25228-9)

3. Pick, C. M., Ko, A., Wormley, A. S., Wiezel, A., Kenrick, D. T., Al-Shawaf, L.,...**Stanciu, A.**...Varnum, M. E. W. (2022). Family still matters: Human social motivation during a global pandemic. Evolution and Human Behavior, 43(6), 527-535. [open access](https://doi.org/10.1016/j.evolhumbehav.2022.09.003)

4. Cari, M.P., Ko, A., Kenrick, D., Wiezel, A., Wormley, A.S., Awad, E...**Stanciu, A**...Varnum, M.E.W. (2022). Fundamental social motives measured across forty-two cultures in two waves. Scientific Data, 9: 499. [open access](https://doi.org/10.1038/s41597-022-01579-w)

## 2021
1. Stanciu, A. (2021). Stereotype accommodation concerning older people. International Journal of Psychology, 57(2), 199-208. [open access](https://t.co/YVNfcrtLc4?amp=1)

2. English, A.S., Xinyi, C.Z., **Stanciu, A.**, Kulich, S.J., Zhao, F., & Bojovic, M. (2021). Ethnic stereotype formation and its impact on sojourner adaptation: A case of "Belt and Road" Chinese migrant workers in Montenegro. International Journal of Environmental Research and Public Health, 18(8), 9540. [open access](https://doi.org/10.3390/ijerph18189540)

## 2020
1. Stanciu, A. (2020). Value systems as motivational forces for the suppression of ageism towards older people amongst young adults: an analysis across countries. Ageing & Society, 42(4), 868-895. [open access](https://doi.org/10.1017/S0144686X20001257)

2. Witte, E.H., **Stanciu, A.*** & Boehnke K. (2020). A new empirical approach to inter-cultural comparisons of value preferences based on Schwartz’s theory. Frontiers in Psychology, Cultural Psychology, 11, 1723. [open access](https://doi.org/10.3389/fpsyg.2020.01723) (*corresponding author)

3. Ko, A., Pick, C.M., Kwon, J.Y., Barlev, M., Krems, J.A., Varnum, M.E.W…**Stanciu, A**...Kenrick, D.T. (2020). Family matters: Rethinking the Psychology of human social motivation. Perspectives on Psychological Science, 15, 173-201. [open access](https://doi.org/10.1177/1745691619872986)

## 2019
1. Stanciu, A., Vauclair, C.-M. & Rodda, N. (2019). Evidence for stereotype accommodation as an expression of immigrants socio-cognitive adaptation. International Journal of Intercultural Relations, 72, 76-86. [open access](https://orbilu.uni.lu/bitstream/10993/60029/1/stanciu%2c%20vauclair%2c%20rodda%2c%202019.pdf)

## 2018
1. Stanciu, A. & Vauclair, C.-M. (2018). Stereotype accommodation: A socio-cognitive perspective on migrants’ cultural adaptation. Journal of Cross-Cultural Psychology, 49, 1027-1047. [open access](https://doi.org/10.1177%2F0022022118777300)

## 2017
1. Stanciu, A. & Vos, M.W. (2017). Stereotype-based faultlines and out-group derogation in diverse teams: The moderating roles of task stereotypicality and need for cognition. The Journal of Social Psychology, 157, 352-365. [open access](https://orbilu.uni.lu/bitstream/10993/60034/1/StanciuVos2017.pdf)

2. Stanciu, A., Cohrs, C.J., Hanke, K. & Gavreliuc, A. (2017). Within-culture variation in the content of stereotypes: Application and development of the stereotype content model in an Eastern European culture. The Journal of Social Psychology, 157, 611-628. [open access](https://www.researchgate.net/publication/310629029_Within-Culture_Variation_in_the_Content_of_Stereotypes_Application_and_Development_of_the_Stereotype_Content_Model_in_an_Eastern_European_Culture)

## 2016
1. Stanciu, A. (2015a). The underlying structure of diverse work groups: A literature review on faultlines and diversity outcomes. Romanian Journal of Applied Psychology, 17, 63-71. [open access](http://www.rjap.psihologietm.ro/Download/rjap172_4.pdf)

2. Stanciu, A. (2015b). Four sub-dimensions of stereotype content: Explanatory evidence from Romania. International Psychology Bulletin, 19, 14-20. [open access](https://www.researchgate.net/publication/306292310_Four_Sub-Dimensions_of_Stereotype_Content_Explanatory_Evidence_from_Romania)

### Pre-prints & working papers

## 2024
1. Stanciu, A. (2024, August 1). Values in psychological network systems compared across groups. <https://osf.io/vewf9>.

2. Stanciu, A., Dominguez-Rodriguez, A., & Westerhof, G. (2024, November 6). Multidimensional determinants to adoption, use and effectiveness of digital technologies for healthy ageing in migrant populations: A scoping review protocol. OSF Preprints. <https://doi.org/10.31219/osf.io/6htuy>. (Study protocol is [registred at OSF Registries](https://doi.org/10.17605/OSF.IO/DWTBY)).

3. Smallenbroek, O., & Stanciu, A. (2024, April 25). Age and gender differences in the value development of dutch adults in 11 years of longitudinal data. SSRN preprints. [preprint available](https://dx.doi.org/10.2139/ssrn.4807701)

5. Smallenbroek., O., Leijen, I., **Stanciu, A.**, van Herk, H., & Bardi, A. (2024, April 15). Constructing Schwartz Values Framework using the Rokeach Values Survey: Human value measurement in the Longitudinal Internet Survey for Social Sciences. OSF Preprints. [preprint available](https://osf.io/preprints/osf/3pqhs)

## 2023
1. Stanciu,  A., Bernardes, M., Partsch, M.V., & Lechner, M. (2023, June 25). Basic human values and the adoption of cryptocurrency. PsyArxiv. [preprint available](https://psyarxiv.com/hxutm/)

2. Witte,  E.H. & Stanciu, A. (2023, June 6).  Error theory of mental test scores without and with  a measuring  instrument. OSF Preprints. [preprint available](https://doi.org/10.31219/osf.io/9ap6m)

## 2020

1. Witte, E.H., **Stanciu, A.**, & Zenker, F. (2020). A simple measure for the predictive accuracy of an empirical construct. PsyArXiv. [preprint available](https://doi.org/10.31234/osf.io/gdmvx)

2. Stanciu, A. (2020). Stereotype accommodation concerning older people. PsyArXiv. [preprint available](https://doi.org/10.31234/osf.io/635qn). <*Now published as [Stanciu (2021)](https://t.co/YVNfcrtLc4?amp=1) @ IJoP.*>

### Books / book chapters

## 2024
1. Hochman, O., **Stanciu, A.**, & Hadjar, A. (Eds.). (2024). 40 Jahre ALLBUS - Die deutsche Gesellschaft im Wandel [40 years of ALLBUS - The German society in transition]. Spinger.

2. Stanciu, A., Hochman, O., & Hadjar, A. (2024). 40 Jahre ALLBUS - Die deutsche Gesellschaft im Wandel (Einleitung) [40 years of ALLBUS - The German society in transition]. In O. Hochman, A. Stanciu & A. Hadjar (Eds.), _40 Jahre ALLBUS - Die deutsche Gesellschaft im Wandel_ (pp. 1-13). Springer.

## 2017 
1. Stanciu, A. (2017). Overall and contextually-bound well-being. Life satisfaction of Romanian migrant-emerging-adults as the outcome of a mediated association acculturation-adaptation. In R. Dimitrova (Ed.), Well-being of Youth and Emerging Adults across Cultures. Springer Series on Cross-Cultural Advancements in Positive Psychology. [open access](pdf/Stanciu_Chapter2017.pdf)

## 2010 
1. Stanciu, A. (2010). Uniforma vestimentară. Ipostază a conformării astăzi. [Dressing uniform. A modern instance of conformity]. Iași, Romania: Lumen. (in Romanian). [behind paywall](https://www.amazon.co.uk/d/cka/Uniforma-vestimentara-Ipostaza-conformarii-astazi-Adrian-Stanciu/9731661999)

### Online / self-published

## 2024
1. Stanciu, A. (2024, June 3). R beyond data analysis. [https://adrian-stanciu.quarto.pub/r-beyond-data-analysis/](https://adrian-stanciu.quarto.pub/r-beyond-data-analysis/) 
:::

___

<a href="#top"> Go to top </a>


