---
title: "Research agenda"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VLRYTQT397"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VLRYTQT397');
</script>

[Ageing, culture, mental health, digital technology.]{style="color: #2a76dd; font-size: 1.5em"}

I focus on identifying and developing inclusive strategies to create sustainable societies in the age of rapid technological growth while an increasing number of international migrants grow old and settle in foreign countries.

## Growing old in a foreign country

The specific risk factors and health needs of people growing old in a foreign country are insufficiently addressed in research, policy making and technology development. This contributes with increased challenges leading to aggravated health inequalities in society. 

With colleagues from different disciplines, including digital health and law, I work on a series of theoretical papers aiming to integrate strands of research on ageing, culture, mental health, and digital technology.

First, we propose a long-term agenda for inclusive assessment, evaluation, and intervention tailored to the health needs in older migrants. This perspective paper integrates perspectives from across disciplines with expertise from the practical sector. 

Second, we introduce in the literature a framework addressing specifics of cultural loneliness in migrants. This theoretical paper describes the processual and long-term development of loneliness in migrants across three stages: initial cultural shock, short term process of adjustment needed to function well, and longer term process of meaning making needed in psychological adaptation.

Third, we introduce in the literature a framework bridging the strands of literature on human development throughout the lifespan with cultural adaptation following international migration. This theoretical paper proposes seeing the migration event as a moment of continuity disruption in the life of people that can result in long-term adaptation or mal-adaptation depending on the available resources. 

## Digital technology and inequalities

Digital technology can offer cost-effective solutions to varying individual and societal challenges including in administration, health, and at work. However, not everyone has access to technology or posses the skills to benefit fully from technology. Specific populations such as migrants and younger and older workers have face unique challenges compared to mainstream majority populations leading to new forms of inequalities.

With colleagues from psychology, technology and science, health, and law, I work on several empirical papers aiming to understanding the limitations of technology in specific populations as well as explore ways to creating more inclusive tools that better serve diverse populations. 

First, we aim to map the existent scientific research on factors that determine adoption, use, and effectiveness of digital technologies to support healthy ageing in migrants. This review paper critically questions the state of our knowledge base in understanding and thus accommodating the specifics of technological solutions for migrants.

Second, we seek to understand longitudinally limitations of transferability of in-person social contact benefits to the digitalized environment. Contact supported by technology can reproduce communication but is ill equipped to reproduce specific forms of human contact, such as touch, that are extremely important for providing social support, for instance, calming the nervous system., 

Third, we propose more inclusive approaches to regulating digital technologies such as the AI in the work space. This policy brief and academic edited book highlights the need to take a more age-specific approach to regulations as each age has unique challenges, for instance, job precarity at younger ages and anxieties associated with skill update common at older age.

___

<a href="#top"> Go to top </a>

