---
title: "Teaching"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VLRYTQT397"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VLRYTQT397');
</script>

## R

(1) Introduction to the R universe - Beyond data analysis

- *Bio*: You might know R from data analysis. But, R can do much more than that for you!
- *Type*: Series of workshops for doctoral students
- *Period*: SoSe 2024 +
- *Institution*: University of Luxembourg, Luxembourg

(2) Introduction to R for quantitative social sciences

- *Bio*: Coverse the basics needed to start using *R* for quantitative research
- *Type*: Online-workshop part of the GESIS training program
- *Period*: 02.02.2022 - 04.02.2022
- *Institution*: GESIS Leibniz Institute for Social Sciences, Germany

## Ageing

(1) Vielfalt der Altersbildern und deren Auswirkung [*Diversity of old age images and outcomes*]

- *Bio*: A brief intro into psychological theories of old age images as well as cross-cultural themes
- *Type*: Online-course; Guest-contribution in eGeneral Studies: Diversity-Kompetenzen
- *Period*: WiSe 2020/21
- *Institution*: University of Bremen, Bremen, Germany

(2) Heterogenität des Alterns aus psychologischer Perspektive [*Heterogeneity of ageing from a psychological perspective*]

- *Bio*:  A discussion on the diversity dimensions of ageing (eg, due to sexual orientation, gender, cultural background) Addresses central theories in developmental, social and cross-cultural psychology
- *Type*: Seminar
- *Period*: SoSe 2019; WiSe 2018/19
- *Institution*: University of Vechta, Vechta, Germany
- *Syllabus*: [here](https://osf.io/ac67f/).

(3) Psychologische Forschung zu Altersbildern-Entstehung und Folgen [*Psychological research to old age images: Causes and outcomes*]

- *Bio*: Discusses social, developmental, and cultural factors that contribute to the emergence of old age stereotype Addresses the impact on well-being, health, and functionality
- *Type*: Seminar
- *Period*: WiSe 2019/20; 2018/19
- *Institution*: University of Vechta, Vechta, Germany
- *Syllabus*: [here](https://osf.io/dzq52/).

## Methods

(1) Deskriptive und inferenzielle Statistik [*Descriptive and inferential statistics*]

- *Bio*: Provides the basics in statistical lingua
- *Type*: Seminar in the Master of Gerontology
- *Period*: WiSe 2024-25 +
- *Institution*: University of Luxembourg, Luxembourg

(2) Psychological network systems

- *Bio*: Introduces psychological network analysis and trains the required programming in R
- *Type*: Seminar in Master of Psychological Assessment.
- *Period*: WiSe 2024-25 +
- *Institution*: University of Luxembourg, Luxembourg


## General topics

(1) Current debates in group processes and intergroup relations

- *Bio*: Discusses key theories in social psychology and gives an introduction to appraoches to solving conflicts
- *Type*: Course; Co-taught with Prof. Christopher J. Cohrs & Dr. Regina Arant (ne Kühl)
- *Period*: WiSe 2017/18
- *Institution*: Jacobs University Bremen, Bremen, Germany


## Practical skills

(1) Introduction to reading and understanding research articles in Psychology (and Social Sciences)

- *Bio*: Provides an overview of the scientific jargon and tips on efficiently extracting the relevant content
- *Type*: Seminar.
- *Period*: WiSe 2019/20; SoSe 2018;2019.
- *Institution*: University of Vechta, Vechta, DE.
- *Syllabus*: [here](https://osf.io/e783s/).

___

<a href="#top"> Go to top </a>


